### ISSUE TITLE
parse/unparse functions prevent plugin from functioning

### ISSUE THREAD

**Issue by tanaes** [snakemake/snakemake-storage-plugin-azure#9]
I've been trying to get up and running with Snakemake 8 on Azure, and independently encountered the error fixed by Pull Request #8.

After fixing that error, trying to launch Snakemake using the plugin yields the following error:

```
(sn-dev) Jons-MacBook-Pro:snakemake-tutorial jgs286$ snakemake --profile Profiles/azure
Using profile Profiles/azure for setting default command line arguments.
Traceback (most recent call last):
  File "/Users/jgs286/Dropbox/Documents/Consulting/Development/Snakemake/snakemake/snakemake/cli.py", line 2047, in main
    success = args_to_api(args, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgs286/Dropbox/Documents/Consulting/Development/Snakemake/snakemake/snakemake/cli.py", line 1779, in args_to_api
    name: StoragePluginRegistry().get_plugin(name).get_settings(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgs286/mambaforge/envs/sn-dev/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 249, in get_settings
    extract_values(item, thefield, name, tag=tag)
  File "/Users/jgs286/mambaforge/envs/sn-dev/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 233, in extract_values
    value = parse_func(value)
            ^^^^^^^^^^^^^^^^^
TypeError: 'ellipsis' object is not callable
```

Commenting out those lines from __init.py__ allowed Snakemake to run, but I was not able to connect to my test Azure Blob:

```
(sn-dev) Jons-MacBook-Pro:snakemake-tutorial jgs286$ snakemake --profile Profiles/azure
Using profile Profiles/azure for setting default command line arguments.
WorkflowError:
Error applying default storage provider azure. Make sure to provide a valid --default-storage-prefix (see https://snakemake.github.io/snakemake-plugin-catalog/plugins/storage/{provider}.html). {validation_res}
```

Not sure if that's due to an error in my specification, but this is what I was using for my profile:

```
use-conda: True
cores: 1
default-storage-provider: azure
default-storage-prefix: snakemake-tutorial
storage-azure-endpoint-url: https://bioinfotest.blob.core.windows.net
storage-azure-sas-token: "se=MYTOKEN"
```

Out of curiosity, has anyone actually used this plugin yet? I'd really love to help with documentation / tutorial if I can get it running.

**Comment by calinanca99** [comment]
Hi @tanaes!

I was wondering if you managed to find a solution for this? I'm currently running into the exact same situation.

**Command executed**:

```bash
snakemake -n --default-storage-provider azure --default-storage-prefix $AZ_DEFAULT_STORAGE_PREFIX \ 
  --storage-azure-endpoint-url $AZ_STORAGE_ENDPOINT_URL \ 
  --storage-azure-access-key $AZ_STORAGE_ACCESS_KEY
```

**Output**:

```bash
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/snakemake-tutorial/lib/python3.12/site-packages/snakemake/cli.py", line 2091, in main
    success = args_to_api(args, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/snakemake-tutorial/lib/python3.12/site-packages/snakemake/cli.py", line 1812, in args_to_api
    name: StoragePluginRegistry().get_plugin(name).get_settings(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/snakemake-tutorial/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 264, in get_settings
    extract_values(item, thefield, name, tag=tag)
  File "/home/ubuntu/mambaforge/envs/snakemake-tutorial/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 243, in extract_values
    value = parse_func(value)
            ^^^^^^^^^^^^^^^^^
TypeError: 'ellipsis' object is not callable
```

As a side-note, if this plugin is not working, then what are the ways in which pipelines can be executed on Azure while also accessing data stored on Azure? Thanks!

**Comment by vsmalladi** [comment]
Same issue. @jakevc any suggestions on  the fix?

**Comment by tanaes** [comment]
I ended up giving up and switching to Nextflow for cloud compute.

**Comment by jakevc** [comment]
Just releasing a fix now.. sorry for the delay
